config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "pages#index"
  get "profile/:id" => "pages#profile", as: :profile

  resources :venues do
    member do
      delete :remove_photo
      delete :remove_primary_photo
    end
    resources :questions, only: [ :create ]
    resources :reviews do
      resources :comments, only: [ :create, :destroy ]
    end
  end

  resources :questions, only: [ :destroy, :edit, :update ] do
    resources :answers, only: [ :create ]
  end

  resources :answers, only: [ :destroy, :edit, :update ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :venue
    belongs_to :user
    has_many :answers, -> { order(created_at: :asc) }, dependent: :destroy

    validates :question, presence: true,
            length: { maximum: 255 }
    validates :venue_id, presence: true
    validates :user_id, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    load_and_authorize_resource

    def create
        @venue = Venue.find(params[:venue_id])
        @question = @venue.questions.create(question_params.merge(user_id: current_user.id))

        if @question.save
            respond_to do |format|
                format.turbo_stream {
                    render turbo_stream: turbo_stream.replace(
                    "questions_section",
                    partial: "questions/questions",
                    locals: { venue: @venue }
                    )
                }
                format.html { redirect_to venue_path(@question.venue) } # fallback
            end
        else
            respond_to do |format|
                format.html { redirect_to venue_path(@venue), alert: "Could not create question" }
            end
        end
    end

    def edit
        @question = Question.find(params[:id])
    end

    def update
        @question = Question.find(params[:id])
        @question.update(question_params)

        respond_to do |format|
            format.turbo_stream {
                render turbo_stream: turbo_stream.replace(
                helpers.dom_id(@question),
                partial: "questions/question",
                locals: { question: @question }
                )
            }
            format.html { redirect_to venue_path(@question.venue) } # fallback
        end
    end


    def destroy
        @question = Question.find(params[:id])

        @question.destroy!
        render turbo_stream: turbo_stream.remove(helpers.dom_id(@question))
    end

    private

    def current_ability
        @current_ability ||= QuestionAbility.new(current_user)
    end

    def question_params
        params.require(:question).permit(:question, :user_id)
    end
end

app/views/questions/_question.html.erb
 <%= turbo_frame_tag dom_id(question) do %>
  <div class="px-3 py-2 shadow-m  bg-base-100 my-6">
    <div class="ml-6 mt-2 flex items-center">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        <div class="w-8 rounded-full">
          <%= comment_avatar(question.user)%>
        </div>
      </div>
      <div class=" text-accent">
        <%=link_to question.user.username, profile_path(question.user.id) %>:
      </div>
    </div>
    <%=turbo_frame_tag "#{dom_id(question)}_content" do %>
      <div class="grid grid-cols-4 gap-10">
        <div class="col-span-3 mt-2 ml-16">
          <p class="italic inline bg-accent/10 text-lg">
            <%= question.question%>
          </p>
        </div>
        <div class="col-span-1 text-center flex">
          <%if current_user == question.user %>
            <div class="block mx-2" >
              <%= link_to "Edytuj", edit_question_path(question), class:"btn btn-md btn-accent"  %>
            </div>
            <div class="mx-2">
              <%= button_to "Usuń", question_path(question), form_class: "btn bg-red-600",
                                                            method: :delete,
                                                            data: { turbo_method: :delete,
                                                            turbo_confirm: "Jesteś pewien ze chcesz usunąć to pytanie?"} %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="flex justify-center text-xs text-accent">
      <%=datetime(question.created_at)%>
    </div>
    <div class="mt-3 px-3 ">
      <div class="mt-2">
        <%if user_signed_in? %>
          <%= render "answers/form", question: question %>
        <% end %>
      </div>
      <%= turbo_frame_tag dom_id(question, :answers) do %>
        <%= render partial: 'answers/answers_list', locals: { answers: question.answers}%>
      <% end%>
    </div>
  </div>
<% end %>

app/views/questions/_question_form.html.erb
<%= form_with(url: venue_questions_path(venue)) do |f| %>
  <label class="form-control w-full">
    <div class="label">
      <%= f.label "Pytania o lokal:", class:"label-text text-sm font-medium" %>
    </div>
    <%= f.text_field :question, name: 'question[question]', class:"input input-bordered w-full bg-white " %>
  </label>
  <div class=" py-2 block">
    <%= f.submit "Zapytaj", class: "btn btn-accent btn-wide btn-xs md:btn-sm lg:btn-md " %>
  </div>
<% end %>

app/views/questions/_questions.html.erb
<%= turbo_frame_tag "questions_section" do %>
  <section id="qestions">
    <div class="m-4">
      <h3 class="text-2xl">
        Pytania:
      </h3>
    </div>
    <div>
      <%if user_signed_in? %>
        <div class="m-4">
          <%= render "questions/question_form", venue: @venue %>
        </div>
      <% end %>
    </div>
    <div>
      <%= render 'questions/questions_list', questions: @venue.questions%>
    </div>
  </section>
<% end %>

app/views/questions/_questions_list.html.erb
<% for question in questions %>
  <%= render question%>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>
<%= turbo_frame_tag "#{dom_id(@question)}_content" do %>
  <%= form_with(model:[@question]) do |f| %>
    <div class="grid grid-cols-4 gap-10">
      <div class="col-span-3 ml-16 " >
        <label class="form-control">
          <%= f.text_field :question, class:"input input-bordered bg-white " %>
        </label>
      </div>
      <div class="col-span-1">
        <div class="col-span-1 text-center flex">
          <div class="block mx-2" >
            <%= link_to :back, class: "btn btn-md bg-red-600 mx-8" do %>
              Cofnij
            <% end %>
          </div>
          <div class="mx-2">
            <%= f.submit "Edytuj", class: "btn btn-accent btn-md" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>