config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "pages#index"
  get "profile/:id" => "pages#profile", as: :profile

  resources :venues do
    member do
      delete :remove_photo
      delete :remove_primary_photo
    end
    resources :questions, only: [ :create ]
    resources :reviews do
      resources :comments, only: [ :create, :destroy ]
    end
  end

  resources :questions, only: [ :destroy, :edit, :update ] do
    resources :answers, only: [ :create ]
  end

  resources :answers, only: [ :destroy, :edit, :update ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    belongs_to :user

    validates :content, presence: true, length: { maximum: 500 }
    validates :question_id, presence: true
    validates :user_id, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    load_and_authorize_resource

    def create
        @question = Question.find(params[:question_id])
        @answer = @question.answers.build(answer_params.merge(user: current_user))


        if @answer.save
            respond_to do |format|
                format.turbo_stream {
                    render turbo_stream: turbo_stream.replace(
                    helpers.dom_id(@question),
                    partial: "questions/question",
                    locals: { question: @question }
                    )
                }
                format.html { redirect_to venue_path(@question.venue) } # fallback
            end
        else
            format.html { redirect_to venue_path(@question.venue), alert: "Nie mozesz odpowiedzieć" }
        end
    end


    def edit
        @answer = Answer.find(params[:id])
    end

    def update
        @answer = Answer.find(params[:id])
        @question = @answer.question
        @answer.update(answer_params)

        respond_to do |format|
            format.turbo_stream {
                render turbo_stream: turbo_stream.replace(
                helpers.dom_id(@answer),
                partial: "answers/answer",
                locals: { answer: @answer }
                )
            }
            format.html { redirect_to venue_path(@question.venue) } # fallback
        end
    end

    def destroy
        @answer = Answer.find(params[:id])
        @answer.destroy!

        render turbo_stream: turbo_stream.remove(helpers.dom_id(@answer))
    end

    private
    def current_ability
        @current_ability ||= AnswerAbility.new(current_user)
    end

    def answer_params
        params.require(:answer).permit(:content)
    end
end

app/views/answers/_answer.html.erb
<%= turbo_frame_tag answer do %>
  <div>
    <div class="ml-14 mt-2 flex items-center">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        <div class="w-8 rounded-full">
          <%= comment_avatar(answer.user)%>
        </div>
      </div>
      <div class=" text-accent">
        <%=link_to answer.user.username, profile_path(answer.user.id), data: {turbo_frame: "_top"} %>:
      </div>
    </div>
    <%=turbo_frame_tag "#{dom_id(answer)}_content" do %>
      <div class="grid grid-cols-4 gap-10">
        <div class="col-span-3 mt-2 ml-24 ">
          <p class="italic inline bg-accent/10 text-lg">
            <%= answer.content%>
          </p>
        </div>
        <div class="col-span-1  text-center flex">
          <%if current_user == answer.user || (current_user && current_user.admin?) || (current_user && current_user.moderator?) %>
            <div class="block mx-2" >
              <%= link_to "Edytuj", edit_answer_path(answer), class:"btn btn-md btn-accent"  %>
            </div>
            <div class="mx-2">
              <%= button_to "Delete",
                    answer_path(answer.id),
                    method: :delete,
                    data: {turbo_confirm:"Jesteś pewien ze chcesz usunąć tę odpowiedź?"},
                    class: "btn btn-md bg-red-600 mx-8" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="flex justify-center text-xs text-accent">
      <%=datetime(answer.created_at)%>
    </div>
  </div>
<% end %>

app/views/answers/_answer_list.html.erb
<% for answer in answers %>
  <%=render answer%>
<%end %>

app/views/answers/_answers_list.html.erb
<% for answer in answers %>
  <%=render answer%>
<%end %>

app/views/answers/_form.html.erb
<% if question.present? %>
  <%= form_with(url: question_answers_path(question)) do |f| %>
    <label class="form-control w-full">
      <div class="label">
        <%= f.label "Odpowiedz:", class:"label-text text-sm font-medium" %>
      </div>
      <%= f.text_field :content, name: 'answer[content]', class:"input input-bordered bg-white" %>
    </label>
    <div class="py-2 block">
      <%= f.submit "Odpowiedz", class: "btn btn-accent btn-wide btn-xs md:btn-sm lg:btn-md" %>
    </div>
  <% end %>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit answer</h1>
<%= turbo_frame_tag "#{dom_id(@answer)}_content" do %>
  <%= form_with(model:[@answer]) do |f| %>
    <div class="grid grid-cols-4 gap-10">
      <div class="col-span-3" >
        <label class="form-control ml-24 min-h-fit">
          <%= f.text_field :content, class:"input input-bordered bg-white " %>
        </label>
      </div>
      <div class="col-span-1">
        <div class="col-span-1  text-center flex">
          <div>
            <%= link_to :back, class: "btn btn-md bg-red-600 mx-8" do %>
              Cofnij
            <% end %>
          </div>
          <div>
            <%= f.submit "Edytuj", class: "btn btn-accent btn-md" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>