config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "pages#index"
  get "profile/:id" => "pages#profile", as: :profile

  resources :venues do
    member do
      delete :remove_photo
      delete :remove_primary_photo
    end
    resources :questions, only: [ :create ]
    resources :reviews do
      resources :comments, only: [ :create, :destroy ]
    end
  end

  resources :questions, only: [ :destroy, :edit, :update ] do
    resources :answers, only: [ :create ]
  end

  resources :answers, only: [ :destroy, :edit, :update ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/venue.rb
class Venue < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy

    has_many :venue_categories
    has_many :categories, through: :venue_categories, dependent: :destroy

    has_many :questions, dependent: :destroy

    has_one_attached :primary_photo
    has_many_attached :photos
    validate :photos_limit


    validates :name, presence: true
    validates :is_active, inclusion: { in: [ true, false ] }
    validates :user_id, presence: true

    scope :active, -> { where(is_active: true) }
    scope :inactive, -> { where(is_active: false) }

    def avg_venue_rating
         reviews.average(:avg_rating)&.round(2) || 0
    end

    def reviews_count
        reviews.size
    end

    def self.most_reviewed_venue
        venue_id_with_most_reviews = Review.group(:venue_id)
                                               .order("COUNT(venue_id) DESC")
                                               .limit(1)
                                               .count
                                               .keys
                                               .first

        return nil unless venue_id_with_most_reviews

        Venue.find_by(id: venue_id_with_most_reviews)
    end

    def self.best_rated_venue
        venue_id_with_best_rating = Review
        .select("venue_id, AVG(reviews.avg_rating) as avg_rating")
        .group(:venue_id)
        .order("avg_rating DESC")
        .first&.venue_id

        return nil unless venue_id_with_best_rating

        Venue.find_by(id: venue_id_with_best_rating)
    end

    def self.search(params)
        params[:query].blank? ? all : where(
            "lower(name) LIKE ?", "%#{sanitize_sql_like((params[:query]).downcase)}%"
        )
    end

    private

    def photos_limit
        if photos.attached? && photos.count > 4
          errors.add(:photos, "Mozesz dodać maksymalnie 4 zdjęcia.")
        end
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  load_and_authorize_resource
  before_action :set_venue, except: [ :index, :show, :new, :create ]
  before_action :set_categories, only: [ :new, :edit ]

  def index
    @venues = Venue.active.includes(:venue_categories, :categories, :reviews).with_attached_primary_photo.search(params)
    @pagy, @venues = pagy(@venues, items: 3)
  end

  def show
    @venue = Venue.includes(:categories, :reviews, :questions).find(params[:id])
    @questions = @venue.questions.includes(:answers)
    @question = Question.new
    @answer = Answer.new
  end

  def new
    @venue = Venue.new()
  end

  def create
    @venue = Venue.new(venue_params.merge(user_id: current_user.id))
    if @venue.save
      redirect_to venues_path
    else
      flash[:alert] = @venue.errors[:photos].any? ? @venue.errors[:photos].join(", ") : "There was an error creating the venue."
      redirect_to new_venue_path
    end
  end

  def edit
    @venue.categories
  end

  def update
    if @venue.update(venue_params)
      redirect_to edit_venue_path(@venue)
      flash[:notice] = "Lokal został pomyślnie zaktualizowany"
    else
      flash[:alert] = @venue.errors[:photos].any? ? @venue.errors[:photos].join(", ") : "There was an error updating the venue."
      redirect_to edit_venue_path(@venue)
    end
  end

  def destroy
    @venue.destroy
    flash[:notice] = "Lokal został pomyślnie usunięty"
    redirect_to :profile
  end

  def remove_photo
    photo = ActiveStorage::Attachment.find(params[:photo_id])
    photo.purge_later
    redirect_to(edit_venue_path(@venue))
  end

  def remove_primary_photo
    primary_photo = ActiveStorage::Attachment.find(params[:primary_photo_id])
    primary_photo.purge_later
    redirect_to(edit_venue_path(@venue))
  end

  private
  def set_venue
    @venue = Venue.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def venue_params
    params.require(:venue).permit(:name, :is_active, :user_id, :primary_photo, :avg_rating, photos: [], category_ids: [])
  end

  def current_ability
    @current_ability ||= VenueAbility.new(current_user)
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
    def datetime(date)
        date.strftime("%d/%m/%Y - %H:%M")
    end

    def check_primary_photo(venue)
        if venue.primary_photo.attached?
          image_tag(venue.primary_photo.variant(resize_to_fill: [ 250, 250 ]).processed, class: "rounded-md m-auto drop-shadow-2xl")
        else
          image_tag("default_primary_photo.webp", width: 250, height: 250, class: "rounded-md m-auto drop-shadow-2xl")

        end
   end

   def check_photo(venue)
      if venue.photos.attached?
        image_tag(venue.photo, class: "rounded-md m-auto drop-shadow-2xl")
      else
        "Lokal nie zawiera zdjęć"
      end
   end

   def primary_photo_in_form(venue)
      if venue.primary_photo.attached?
        image_tag(venue.primary_photo.variant(resize_to_fill: [ 200, 200 ]).processed, class: "mx-auto object-cover my-5")
      else
        "Zdjęcie nie zostało dodane"
      end
   end

   def photo_in_form(photo)
      image_tag(photo.variant(resize_to_fill: [ 300, 300 ]).processed, class: "mx-auto object-cover my-5")
   end

   def check_reviews(venue)
      if venue.reviews.count == 0
        ""
      else
        "( %s in %s Reviews )" % [ venue.avg_venue_rating, venue.reviews_count ]
      end
   end

  def comment_avatar(user)
    if user.avatar.attached?
      image_tag(user.avatar.variant(resize_and_pad: [ 500, 500 ]))
    else
      image_tag("default_avatar.png")
    end
  end

  def review_avatar(user)
    if user.avatar.attached?
      image_tag(user.avatar.variant(resize_and_pad: [ 500, 500 ]))
    else
      image_tag("default_avatar.png")
    end
  end
end

app/views/venues/_form.html.erb
<%= form_with(model: venue) do |form| %>
  <div class="grid grid-cols-2 gap-x-8 justify-items-stretch ">
    <div class= "col-span-1">
      <div>
        <label class="form-control w-full max-w-xs">
          <div class="label">
            <%= form.label :name, "Nazwa lokalu", class:"label-text text-lg" %>
          </div>
          <%= form.text_field :name, class:"input input-bordered w-full max-w-xs" %>
        </label>
      </div>
      <div class= "my-3 w-full max-w-4xl dark:bg-surface-dark ">
        <div class="form-control">
          <div class= "label ">
            <%= form.label :categories, "Kategorie", class:"label-text text-lg"%>
          </div>
          <div class="grid grid-cols-2 gap-x-2 gap-y-2 ">
            <% Category.all.each do |category| %>
              <div class="label cursor-pointer border-2 rounded-full bg-base-100 ">
                <span class="label-text pl-2">
                  <%= label_tag "venue_category_ids_#{category.id}", category.name%>
                </span>
                <%= check_box_tag 'venue[category_ids][]', category.id, @venue.category_ids.include?(category.id), class: "checkbox border-amber-700 [--chkbg:theme(colors.base-300)] [--chkfg:orange] checked:border-amber-700"  %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class= "col-span-1 justify-self-center">
      <div>
        <label class="form-control w-full max-w-xs">
          <div class="label">
            <%= form.label :primary_photo, "Zdjęcie główne", class:"label-text text-lg" %>
          </div>
          <div class="field p-3 my-3 w-full max-w-4xl">
            <div class="">
              <%= primary_photo_in_form(@venue)%>
              <% if @venue.primary_photo.attached?%>
                <%=link_to "Usuń", remove_primary_photo_venue_path(@venue, primary_photo_id: @venue.primary_photo.id), data: {confirm: "Are You sure?", turbo_method: :delete}, class: "mt-2 text-red-700"%>
              <% end%>
            </div>
            <%= form.file_field :primary_photo, class:"file-input file-input-bordered w-full max-w-xs" %>
          </label>
        </div>
      </div>
      <div>
        <label class="form-control w-full max-w-xs">
          <div class="mt-2">
            <div class="label">
              <%= form.label :photos, "Zdjęcia lokalu", class:"label-text text-lg" %>
              <div class="text-xs">
                Maksymalnie 4 zdjęcia
              </div>
            </div>
          </div>
          <div class="field p-3 my-3 w-full max-w-4xl">
            <div class="grid grid-cols-2 gap-4 p-3">
              <% if @venue.photos.attached?%>
                <% @venue.photos.each do |photo| %>
                  <%= form.hidden_field :photos, multiple: true, value: photo.signed_id %>
                  <div>
                    <%= photo_in_form(photo)%>
                    <div class="text-center">
                      <%=link_to "Usuń", remove_photo_venue_path(@venue, photo_id: photo), data: {confirm: "Are You sure?", turbo_method: :delete}, class: "mt-2 text-red-700"%>
                    </div>
                  </div>
                <% end %>
              <%end %>
            </div>
            <%= form.file_field :photos, multiple: true, class:"file-input file-input-bordered w-full max-w-xs" %>
          </div>
        </label>
      </div>
    </div>
  </div>
  <% if action_name == 'new' %>
    <div class="text-xs my-2">
      <p>Po stworzeniu swojego lokalu, będzie on widoczny tylko dla Ciebie. Aktywuj go w swoim profilu</p>
    </div>
    <div class="flex justify-center">
      <button class="btn btn-accent btn-wide btn-xs sm:btn-sm md:btn-md lg:btn-lg">
        <%= form.submit%>
      </button>
    </div>
  <% else %>
    <div class="my-2">
      <div class="form-control">
        <label class="label cursor-pointer mx-auto">
          <span class="label-text px-4">
            <%= form.label :is_active, "Czy Twój lokal jest aktywny?" %>
          </span>
          <%= form.check_box :is_active, class: "checkbox border-amber-700 [--chkbg:theme(colors.base-300)] [--chkfg:orange] checked:border-amber-700" %>
        </label>
      </div>
      <div class="flex justify-center">
        <button class="btn btn-accent btn-wide btn-xs sm:btn-sm md:btn-md lg:btn-lg">
          <%= form.submit%>
        </button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/venues/_venues_list.html.erb
<div class="grid grid-cols-12 gap-6">
  <% if @venues.count == 0  %>
    <div class="col-span-12">Nie znaleźliśmy lokalu którego szukasz</div>
  <% else %>
    <% @venues.each do |venue| %>
      <div class="col-span-12">
        <div class="w-full max-w-6xl  shadow-md rounded-lg dark:bg-surface-dark border min-h-32 bg-base-100">
          <div class="grid grid-cols-12">
            <div class="col-span-4">
              <div class="relative bg-cover bg-no-repeat p-3">
                <%= check_primary_photo(venue)%>
                <div class="absolute bottom-0 left-0 right-0 top-0 h-full w-full overflow-hidden bg-[hsla(0,0%,98%,0.15)] bg-fixed opacity-0 transition duration-300 ease-in-out hover:opacity-100">
                </div>
              </div>
            </div>
            <div class="col-span-8">
              <div class="p-6 text-surface">
                <div class="flex">
                  <h3 class="text-l font-medium">
                    <%= link_to venue.name, venue_path(venue), data: { turbo_frame: "_top"} %>
                    <div class="inline">
                      <%= check_reviews(venue) %>
                    </div>
                  </h3>
                  <div class="">
                  </div>
                </div>
                <div class="text-xs italic">
                  <% for category in venue.categories%>
                    <%= category.name %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <%end %>
  <% end %>
  <div class="col-span-12 justify-items-center">
    <div class="my-2 ">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/venues/edit.html.erb
<div class="flex flex-col min-h-screen bg-base-200 py-8 ">
  <div class=" mx-auto text-center">
    <div class="text-2xl">
      Edytuj swój lokal
    </div>
  </div>
  <div class="mx-10 ">
    <%= render 'form', venue: @venue %>
  </div>
</div>

app/views/venues/index.html.erb
<div class="flex flex-col items-center min-h-screen bg-base-200 py-8 px-16">
  <div class="w-full ">
    <%= form_tag venues_path, method: :get, data: { turbo_frame: "search-results", turbo_action: "advance",
     controller: "search", action: "input->search#submit"} do |f|%>
      <%= text_field_tag "query", nil, placeholder: "Wyszukaj lokal ...", class:"input w-full my-5 enabled:hover:bg-slate-200"%>
    <% end %>
  </div>
  <div class="grid grid-cols-12 gap-2 w-full ">
    <div class="col-span-8">
      <%= turbo_frame_tag "search-results" do %>
        <%=render partial: 'venues/venues_list', locals: { venues: @venues}%>
      <% end %>
    </div>
    <div id="menu" class="col-span-4 h-72 border bg-base-100">
      <div class="">
        <div class="m-2">
          <div>
            Search console
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/venues/new.html.erb
<div class="flex flex-col min-h-screen bg-base-200 py-8 ">
  <div class="mx-auto text-center ">
    <div class="text-2xl">
      Dodaj swój lokal
    </div>
  </div>
  <div class="mx-10 ">
    <%= render 'form', venue: @venue %>
  </div>
</div>

app/views/venues/show.html.erb
<div class="flex flex-col items-center min-h-screen bg-base-200 py-4 px-20">
  <div class="grid grid-cols-12 gap-4 w-full">
    <div class="col-span-4 border p-4  max-w-4xl min-w-96 min-h-64 bg-base-100 shadow-md rounded-lg">
      <div>
        <div class="text-2xl">
          <% if @venue.reviews.count != 0 %>
            <%= @venue.name %> (<%= @venue.avg_venue_rating%> / 6.0)
          <% else %>
            <%= @venue.name %>
            <div class="text-xs">
              Oceń jako pierwszy
            </div>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <button class="btn btn-accent btn-sm ">
            <%=link_to "Oceń", new_venue_review_path(@venue), class: "block px-6" %>
          </button>
        <% end %>
        <div>
          <div class="relative bg-cover bg-no-repeat p-3 ">
            <%= check_primary_photo(@venue)%>
          </div>
        </div>
        <div class="mt-2 flex divide-x-2">
          <% for category in @venue.categories %>
            <div class="text-sm px-2 text-accent">
              <%=category.name%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-span-8 w-full max-w-4xl bg-base-100 shadow-md rounded-lg border min-h-64">
      <div class="text-lg p-3">
        Zdjęcia:
      </div>
      <div>
        <% if @venue.photos.attached? %>
          <div class="grid grid-cols-2">
            <% @venue.photos.each do |photo| %>
              <div class="relative bg-cover bg-no-repeat p-2">
                <%= image_tag(photo.variant(resize_to_fill:[300, 250]).processed, class: "mx-auto object-cover") %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-span-12 w-full min-h-64">
      <div class="mb-5 p-4 ">
        <h3 class="text-2xl ">
          Recenzje:
        </h3>
      </div>
      <% if @venue.reviews.count == 0 %>
        <div class="text-center">
          <p class="text-2xl">
            Brak recenzji
          </p>
        </div>
      <%end%>
      <% for review in @venue.reviews %>
        <div class="mb-10 bg-base-100 border p-4">
          <div class="float-end ">
            <div class="flex  ">
              <%=review.comments.count %> <img src="<%= asset_path('comment.svg') %>" class="max-w-4 mx-1" alt="Your SVG">
            </div>
          </div>
          <div class="mb-2 text-xl flex items-center">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
              <div class="w-8 rounded-full">
                <%= review_avatar(review.user)%>
              </div>
            </div>
            <div>
              <%=link_to review.user.username, profile_path(review.user.id) %>
            </div>
          </div>
          <div class="my-4 px-3 text-3xl text-center">
            <%=link_to review.title, venue_review_path(@venue, review) %>
          </div>
          <div class="my-4 px-10">
            <p class="text-sm leading-5 text-pretty line-clamp-4 indent-4">
              <%= review.content %>
            </p>
          </div>
          <div class="border-t py-2">
            <div class="text-center text-xl">
              (<%=review.avg_review_rating%> / 6)
            </div>
            <div class="flex text-center justify-evenly mt-2">
              <% review.rating_dictionary.each do |category, rating| %>
                <div class="">
                  <div class="">
                    <%= category %>
                  </div>
                  <div class="">
                    <%= rating %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-span-12 w-full border min-h-64">
      <div>
        <%= render 'questions/questions', venue: @venue%>
      </div>
    </div>
  </div>
</div>