config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "pages#index"
  get "profile/:id" => "pages#profile", as: :profile

  resources :venues do
    member do
      delete :remove_photo
      delete :remove_primary_photo
    end
    resources :questions, only: [ :create ]
    resources :reviews do
      resources :comments, only: [ :create, :destroy ]
    end
  end

  resources :questions, only: [ :destroy, :edit, :update ] do
    resources :answers, only: [ :create ]
  end

  resources :answers, only: [ :destroy, :edit, :update ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_footer.html.erb
<footer class="footer footer-center bg-base-300 text-base-content rounded-sm p-10">
  <p class="text-xs">This is demo version of knajping app, test it out and check for updates </p>
  <nav class="grid grid-flow-col gap-4">
    <a class="link link-hover">About us</a>
    <a class="link link-hover">Contact</a>
  </nav>
  <aside>
    <p>Copyright © 2025 - All right reserved by <a href="https://maciejbentkowski.pl" target="_blank">Maciej Bentkowski</a></p>
  </aside>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar bg-base-300">
    <div class="navbar-start">
      <div class="flex md:hidden">
        <div class="dropdown">
          <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
            </svg>
          </div>
          <ul tabindex="0" class="menu menu-md dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow-sm">
            <% if user_signed_in? %>
              <li>
                <%=link_to "Lokale", venues_path%>
              </li>
            <% else %>
              <li>
                <%=link_to "Lokale", venues_path%>
              </li>
              <li>
                <a>Logowanie:</a>
                <ul>
                  <li>
                    <%=link_to "Zaloguj się", new_user_session_path%>
                  </li>
                  <li>
                    <%=link_to "Zarejestruj się", new_user_registration_path%>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="hidden md:flex">
        <%= link_to "Knajping", root_path, :class => "btn btn-ghost text-xl"%>
      </div>
    </div>
    <div class="navbar-center ">
      <div class="hidden md:flex">
        <ul class="menu menu-lg menu-horizontal px-1">
          <li><%=link_to "Lokale", venues_path %></li>
        </ul>
      </div>
      <div class="flex md:hidden">
        <%= link_to "Knajping", root_path, :class => "btn btn-ghost text-xl"%>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="navbar-end">
        <div class="hidden md:block pr-10 text-black/80">
          Cześć, <%= current_user.username %>
        </div>
        <div class="flex-none gap-2">
          <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <%= header_avatar()%>
              </div>
            </div>
            <ul tabindex="0" class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow-sm">
              <li>
                <%=link_to "Profil", profile_path(current_user)%>
              </li>
              <li>
                <%=link_to "Stwórz Lokal", new_venue_path%>
              </li>
              <li>
                <%=button_to "Wyloguj się", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% else %>
      <div class="navbar-end">
        <div class="hidden md:flex ">
          <ul class="menu menu-horizontal px-1">
            <li>
              <%=link_to "Zaloguj się", new_user_session_path%>
            </li>
            <li>
              <%=link_to "Zarejestruj się", new_user_registration_path%>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title><%= content_for(:title) || "Knajping" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render partial: 'layouts/header' %>
    <div>
      <% if notice %>
        <div role="alert" class="alert alert-success">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span><%= notice %></span>
        </div>
      <% elsif alert%>
        <div role="alert" class="alert alert-error">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span><%= alert %></span>
        </div>
      <%end%>
    </div>
    <main class="flex flex-col min-h-screen">
      <%= yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>